# Changes here will be overwritten by Copier
_commit: 0.1.1
_src_path: template
project_authors:
- '  {name = "m09", email = "142691+m09@users.noreply.github.com"},'
project_description: Implementation and testing of a Caesar cipher.
project_homepage: https://github.com/shuuchuu/caesar-cipher
project_id: caesar_cipher
project_license: Apache-2.0
project_name: caesar-cipher
tools:
- devcontainer
- pytest
